-- Generated by Oracle SQL Developer Data Modeler 21.2.0.183.1957
--   at:        2024-12-18 18:54:49 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE danie (
    id_dania     NUMBER NOT NULL,
    nazwa_dania  VARCHAR2(20),
    opis         VARCHAR2(20),
    cena         VARCHAR2(20),
    dostêpnoœæ   VARCHAR2(20),
    produkty     VARCHAR2(20),
    menu_id_menu NUMBER
);

ALTER TABLE danie ADD CONSTRAINT danie_pk PRIMARY KEY ( id_dania );

CREATE TABLE dostawcy (
    id_dostawcy                   NUMBER NOT NULL,
    imiê                          VARCHAR2(20),
    nazwisko                      VARCHAR2(20),
    telefon                       NUMBER(9),
    numer_rejestracyjny_samochodu NUMBER,
    kierownik_id_kierownika       NUMBER NOT NULL
);

ALTER TABLE dostawcy ADD CONSTRAINT dostawcy_pk PRIMARY KEY ( id_dostawcy );

CREATE TABLE kierownik (
    id_kierownika NUMBER NOT NULL,
    imiê          VARCHAR2(20),
    nazwisko      VARCHAR2(20),
    telefon       NUMBER(9),
    pesel         NUMBER(11)
);

ALTER TABLE kierownik ADD CONSTRAINT kierownik_pk PRIMARY KEY ( id_kierownika );

CREATE TABLE klienci (
    id_klienta NUMBER NOT NULL,
    imiê       VARCHAR2(20),
    nazwisko   VARCHAR2(20),
    telefon    NUMBER(9)
);

ALTER TABLE klienci ADD CONSTRAINT klienci_pk PRIMARY KEY ( id_klienta );

CREATE TABLE menu (
    id_menu           NUMBER NOT NULL,
    lista_dañ         VARCHAR2(20),
    data_aktualizacji VARCHAR2(20)
);

ALTER TABLE menu ADD CONSTRAINT menu_pk PRIMARY KEY ( id_menu );

CREATE TABLE p³atnoœci (
    id_p³atnoœci         NUMBER NOT NULL,
    id_rachunku_1        NUMBER,
    data_p³atnoœci       DATE,
    godzina              DATE,
    kwota                NUMBER,
    metoda_p³atnoœci     VARCHAR2(20),
    rachunki_id_rachunku NUMBER NOT NULL
);

CREATE UNIQUE INDEX p³atnoœci__idx ON
    p³atnoœci (
        rachunki_id_rachunku
    ASC );

ALTER TABLE p³atnoœci ADD CONSTRAINT p³atnoœci_pk PRIMARY KEY ( id_p³atnoœci );

CREATE TABLE pracownicy (
    id_pracownika           NUMBER NOT NULL,
    imiê                    VARCHAR2(20),
    nazwisko                VARCHAR2(20),
    rola                    VARCHAR2(20),
    telefon                 NUMBER(9),
    pesel                   NUMBER(11),
    kierownik_id_kierownika NUMBER
);

ALTER TABLE pracownicy ADD CONSTRAINT pracownicy_pk PRIMARY KEY ( id_pracownika );

CREATE TABLE rachunki (
    id_rachunku              NUMBER NOT NULL,
    id_klienta               NUMBER,
    data_zamówienia          DATE,
    godzina                  DATE,
    status                   VARCHAR2(20),
    pracownicy_id_pracownika NUMBER NOT NULL
);

ALTER TABLE rachunki ADD CONSTRAINT rachunki_pk PRIMARY KEY ( id_rachunku );

CREATE TABLE relation_1 (
    klienci_id_klienta       NUMBER NOT NULL,
    rezerwacje_id_rezerwacji NUMBER NOT NULL
);

ALTER TABLE relation_1 ADD CONSTRAINT relation_1_pk PRIMARY KEY ( klienci_id_klienta,
                                                                  rezerwacje_id_rezerwacji );

CREATE TABLE rezerwacje (
    id_rezerwacji      NUMBER NOT NULL,
    id_klienta         NUMBER,
    data_rezerwacji    DATE,
    godzina            DATE,
    iloœæ_osób         INTEGER,
    status             VARCHAR2(20),
    stoliki_id_stolika NUMBER
);

ALTER TABLE rezerwacje ADD CONSTRAINT rezerwacje_pk PRIMARY KEY ( id_rezerwacji );

CREATE TABLE sk³adniki (
    id_sk³adnika         VARCHAR2(20) NOT NULL,
    nazwa                VARCHAR2(20),
    gramatura            FLOAT,
    dostawcy_id_dostawcy NUMBER NOT NULL,
    danie_id_dania       NUMBER
);

ALTER TABLE sk³adniki ADD CONSTRAINT sk³adniki_pk PRIMARY KEY ( id_sk³adnika );

CREATE TABLE stoliki (
    id_stolika           NUMBER NOT NULL,
    numer_stolika        VARCHAR2(20),
    liczba_miejsc        VARCHAR2(20),
    status               VARCHAR2(20),
    rachunki_id_rachunku NUMBER NOT NULL
);

CREATE UNIQUE INDEX stoliki__idx ON
    stoliki (
        rachunki_id_rachunku
    ASC );

ALTER TABLE stoliki ADD CONSTRAINT stoliki_pk PRIMARY KEY ( id_stolika );

ALTER TABLE danie
    ADD CONSTRAINT danie_menu_fk FOREIGN KEY ( menu_id_menu )
        REFERENCES menu ( id_menu );

ALTER TABLE dostawcy
    ADD CONSTRAINT dostawcy_kierownik_fk FOREIGN KEY ( kierownik_id_kierownika )
        REFERENCES kierownik ( id_kierownika );

ALTER TABLE p³atnoœci
    ADD CONSTRAINT p³atnoœci_rachunki_fk FOREIGN KEY ( rachunki_id_rachunku )
        REFERENCES rachunki ( id_rachunku );

ALTER TABLE pracownicy
    ADD CONSTRAINT pracownicy_kierownik_fk FOREIGN KEY ( kierownik_id_kierownika )
        REFERENCES kierownik ( id_kierownika );

ALTER TABLE rachunki
    ADD CONSTRAINT rachunki_pracownicy_fk FOREIGN KEY ( pracownicy_id_pracownika )
        REFERENCES pracownicy ( id_pracownika );

ALTER TABLE relation_1
    ADD CONSTRAINT relation_1_klienci_fk FOREIGN KEY ( klienci_id_klienta )
        REFERENCES klienci ( id_klienta );

ALTER TABLE relation_1
    ADD CONSTRAINT relation_1_rezerwacje_fk FOREIGN KEY ( rezerwacje_id_rezerwacji )
        REFERENCES rezerwacje ( id_rezerwacji );

ALTER TABLE rezerwacje
    ADD CONSTRAINT rezerwacje_stoliki_fk FOREIGN KEY ( stoliki_id_stolika )
        REFERENCES stoliki ( id_stolika );

ALTER TABLE sk³adniki
    ADD CONSTRAINT sk³adniki_danie_fk FOREIGN KEY ( danie_id_dania )
        REFERENCES danie ( id_dania );

ALTER TABLE sk³adniki
    ADD CONSTRAINT sk³adniki_dostawcy_fk FOREIGN KEY ( dostawcy_id_dostawcy )
        REFERENCES dostawcy ( id_dostawcy );

ALTER TABLE stoliki
    ADD CONSTRAINT stoliki_rachunki_fk FOREIGN KEY ( rachunki_id_rachunku )
        REFERENCES rachunki ( id_rachunku );



-- Oracle SQL Developer Data Modeler Summary Report:
--
-- CREATE TABLE                            12
-- CREATE INDEX                             2
-- ALTER TABLE                             23
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
--
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
--
-- REDACTION POLICY                         0
--
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
--
-- ERRORS                                   0
-- WARNINGS                                 0

INSERT INTO WORKERS(W_ID,FIRST_NAME, LAST_NAME, SALARY, BOSS_ID)
VALUES(18, 'ELO', 'ELO',4500, NULL);

--DANIE--------------------

INSERT INTO DANIE(ID_DANIA, NAZWA_DANIA, OPIS, CENA, DOSTÊPNOŒÆ, PRODUKTY, MENU_ID_MENU)
VALUES(1, 'ROSÓ£', 'ZUPA Z KURY', 15, 'ZAWSZE', 'BULION, MAKARON', 1);

INSERT INTO DANIE(ID_DANIA, NAZWA_DANIA, OPIS, CENA, DOSTÊPNOŒÆ, PRODUKTY, MENU_ID_MENU)
VALUES(2, 'POMODORO', 'ZUPA Z POMIDORA', 15, 'ZAWSZE', 'BULION, POMODORO', 1);

INSERT INTO DANIE(ID_DANIA, NAZWA_DANIA, OPIS, CENA, DOSTÊPNOŒÆ, PRODUKTY, MENU_ID_MENU)
VALUES(3, 'SCHABOSZCZAK', 'MIÊSO ZE ŒWINI', 33, 'ZAWSZE', 'SCHAB, ZIEMNIAKI', 1);

INSERT INTO DANIE(ID_DANIA, NAZWA_DANIA, OPIS, CENA, DOSTÊPNOŒÆ, PRODUKTY, MENU_ID_MENU)
VALUES(4, 'PIEROGSY', 'PIEROGI Z MIÊSEM', 28, 'SPYTAJ KELNERA', 'CIASTO, MIÊSO', 1);

INSERT INTO DANIE(ID_DANIA, NAZWA_DANIA, OPIS, CENA, DOSTÊPNOŒÆ, PRODUKTY, MENU_ID_MENU)
VALUES(5, 'FRYTKI', 'ZIEMNIAKI/BATATY', 20, 'ZAWSZE', 'ZIEMNIAKI, KECZUP', 1);

UPDATE DANIE
SET MENU_ID_MENU = 1;

--DOSTAWCY------------------
ALTER TABLE DOSTAWCY
MODIFY NUMER_REJESTRACYJNY_SAMOCHODU VARCHAR(15);

DELETE FROM DOSTAWCY;

INSERT INTO DOSTAWCY(ID_DOSTAWCY, IMIÊ, NAZWISKO, TELEFON, NUMER_REJESTRACYJNY_SAMOCHODU, KIEROWNIK_ID_KIEROWNIKA, id_samochodu)
VALUES(1, 'JANUSZ', 'MA£YSZ', 555555555, 'PO10001', 1, id_samochodu_seq.NEXTVAL);

INSERT INTO DOSTAWCY(ID_DOSTAWCY, IMIÊ, NAZWISKO, TELEFON, NUMER_REJESTRACYJNY_SAMOCHODU, KIEROWNIK_ID_KIEROWNIKA,id_samochodu)
VALUES(2, 'BART£OMIEJ', 'GA£¥ZKA', 837428283, 'PO12340', 1, id_samochodu_seq.NEXTVAL);


INSERT INTO DOSTAWCY(ID_DOSTAWCY, IMIÊ, NAZWISKO, TELEFON, NUMER_REJESTRACYJNY_SAMOCHODU, KIEROWNIK_ID_KIEROWNIKA,id_samochodu)
VALUES(3, 'IGOR', 'POZNAÑSKI', 666666666, 'PO54671', 1, id_samochodu_seq.NEXTVAL);


INSERT INTO DOSTAWCY(ID_DOSTAWCY, IMIÊ, NAZWISKO, TELEFON, NUMER_REJESTRACYJNY_SAMOCHODU, KIEROWNIK_ID_KIEROWNIKA,id_samochodu)
VALUES(4, 'BARTOSZ', 'MA£OMIEJSKI', 198765432, 'PO18201', 1, id_samochodu_seq.NEXTVAL);


INSERT INTO DOSTAWCY(ID_DOSTAWCY, IMIÊ, NAZWISKO, TELEFON, NUMER_REJESTRACYJNY_SAMOCHODU, KIEROWNIK_ID_KIEROWNIKA,id_samochodu)
VALUES(5, 'MARCELI', 'TORUÑSKI', 571885555, 'PO25001', 1, id_samochodu_seq.NEXTVAL);

--KIEROWNIK-----------------
INSERT INTO KIEROWNIK(ID_KIEROWNIKA, IMIÊ, NAZWISKO, TELEFON, PESEL)
VALUES(1, 'AREK', 'LODO£AMACZ', 123123123, 12345678911);



--KLIENCI--------------------
DELETE FROM KLIENCI;
INSERT INTO KLIENCI(ID_KLIENTA, IMIÊ, NAZWISKO, TELEFON)
VALUES(10, 'EDYTA', 'NEKIELSKA', 987098456);

INSERT INTO KLIENCI(ID_KLIENTA, IMIÊ, NAZWISKO, TELEFON)
VALUES(11, 'JULITA', 'TAKA', 765123123);

INSERT INTO KLIENCI(ID_KLIENTA, IMIÊ, NAZWISKO, TELEFON)
VALUES(12, 'MAGDA', 'JAKA', 358456654);

INSERT INTO KLIENCI(ID_KLIENTA, IMIÊ, NAZWISKO, TELEFON)
VALUES(13, 'KLAUDIA', 'BAROWA', 234432234);

INSERT INTO KLIENCI(ID_KLIENTA, IMIÊ, NAZWISKO, TELEFON)
VALUES(14, 'OLENA', 'KRAKOWSKA', 876876123);

--MENU--------------------------------------------------
ALTER TABLE MENU
MODIFY LISTA_DAÑ VARCHAR2(60);

INSERT INTO MENU(ID_MENU, LISTA_DAÑ, DATA_AKTUALIZACJI)
VALUES(1, 'ROSÓ£, POMIDORO, FRYTKI, PIEROGSY, SCHABOSZCZAK', '2021-01-05');



--P£ATNOŒCI
ALTER TABLE P£ATNOŒCI
MODIFY GODZINA VARCHAR2(60);

ALTER TABLE P£ATNOŒCI
DROP COLUMN ID_RACHUNKU_1;

INSERT INTO P£ATNOŒCI(ID_P£ATNOŒCI, ID_RACHUNKU_1, DATA_P£ATNOŒCI, GODZINA, KWOTA, METODA_P£ATNOŒCI, RACHUNKI_ID_RACHUNKU)
VALUES(1, 1, '2024-12-12', '15:21', 65 , 'KARTA', 1);

INSERT INTO P£ATNOŒCI(ID_P£ATNOŒCI, ID_RACHUNKU_1, DATA_P£ATNOŒCI, GODZINA, KWOTA, METODA_P£ATNOŒCI, RACHUNKI_ID_RACHUNKU)
VALUES(2, 2, '2024-12-11', '16:43', 106, 'KARTA', 2);

INSERT INTO P£ATNOŒCI(ID_P£ATNOŒCI, ID_RACHUNKU_1, DATA_P£ATNOŒCI, GODZINA, KWOTA, METODA_P£ATNOŒCI, RACHUNKI_ID_RACHUNKU)
VALUES(3, 3, '2022-11-12', '17:18', 122, 'GOTÓWKA', 3);

INSERT INTO P£ATNOŒCI(ID_P£ATNOŒCI, ID_RACHUNKU_1, DATA_P£ATNOŒCI, GODZINA, KWOTA, METODA_P£ATNOŒCI, RACHUNKI_ID_RACHUNKU)
VALUES(4, 4, '2023-10-12', '20:12', 45, 'KARTA', 4);

INSERT INTO P£ATNOŒCI(ID_P£ATNOŒCI, ID_RACHUNKU_1, DATA_P£ATNOŒCI, GODZINA, KWOTA, METODA_P£ATNOŒCI, RACHUNKI_ID_RACHUNKU)
VALUES(5, 5, '2021-12-12', '17:50', 187, 'GOTÓWKA', 5);



--PRACOWNICY
INSERT INTO PRACOWNICY(ID_PRACOWNIKA, IMIÊ, NAZWISKO, ROLA, TELEFON, PESEL, KIEROWNIK_ID_KIEROWNIKA)
VALUES(30, 'EDYTA', 'KONIECZNA', 'KELNER', 432456789, 90987667843, 1);

INSERT INTO PRACOWNICY(ID_PRACOWNIKA, IMIÊ, NAZWISKO, ROLA, TELEFON, PESEL, KIEROWNIK_ID_KIEROWNIKA)
VALUES(31, 'ANTONI', 'KOSIBA', 'KELNER', 929615473, 98712345672, 1);

INSERT INTO PRACOWNICY(ID_PRACOWNIKA, IMIÊ, NAZWISKO, ROLA, TELEFON, PESEL, KIEROWNIK_ID_KIEROWNIKA)
VALUES(32, 'ANNA', 'WESO£OWSKA', 'KELNER', 967567432, 99887766554, 1);

INSERT INTO PRACOWNICY(ID_PRACOWNIKA, IMIÊ, NAZWISKO, ROLA, TELEFON, PESEL, KIEROWNIK_ID_KIEROWNIKA)
VALUES(33, 'MAKSYMILIAN', '£AKOMY', 'BARMAN', 787454323, 99007744345, 1);

INSERT INTO PRACOWNICY(ID_PRACOWNIKA, IMIÊ, NAZWISKO, ROLA, TELEFON, PESEL, KIEROWNIK_ID_KIEROWNIKA)
VALUES(34, 'JAKUB', 'NIEPEWNY', 'RECEPCJONISTA', 919282545, 98767854321, 1);


--RACHUNKI-----------------------
DELETE FROM RACHUNKI;

ALTER TABLE RACHUNKI
MODIFY GODZINA VARCHAR2(10);

INSERT INTO RACHUNKI(ID_RACHUNKU, ID_KLIENTA, DATA_ZAMÓWIENIA, GODZINA, STATUS, PRACOWNICY_ID_PRACOWNIKA)
VALUES(1, 10, '2024-12-12', '12:00', 'OP£ACONE', 30);

INSERT INTO RACHUNKI(ID_RACHUNKU, ID_KLIENTA, DATA_ZAMÓWIENIA, GODZINA, STATUS, PRACOWNICY_ID_PRACOWNIKA)
VALUES(2, 11, '2024-12-11', '12:30', 'OP£ACONE', 31);

INSERT INTO RACHUNKI(ID_RACHUNKU, ID_KLIENTA, DATA_ZAMÓWIENIA, GODZINA, STATUS, PRACOWNICY_ID_PRACOWNIKA)
VALUES(3, 12, '2022-11-12', '13:00', 'OP£ACONE', 32);

INSERT INTO RACHUNKI(ID_RACHUNKU, ID_KLIENTA, DATA_ZAMÓWIENIA, GODZINA, STATUS, PRACOWNICY_ID_PRACOWNIKA)
VALUES(4, 13, '2023-10-12', '12:00', 'OP£ACONE', 33);

INSERT INTO RACHUNKI(ID_RACHUNKU, ID_KLIENTA, DATA_ZAMÓWIENIA, GODZINA, STATUS, PRACOWNICY_ID_PRACOWNIKA)
VALUES(5, 14, '2021-12-12', '14:00', 'OP£ACONE', 34);

--REZERWACJE-------------------
ALTER TABLE REZERWACJE
MODIFY GODZINA VARCHAR2(10);

DELETE FROM REZERWACJE;
INSERT INTO REZERWACJE(ID_REZERWACJI, ID_KLIENTA, DATA_REZERWACJI, GODZINA, ILOŒÆ_OSÓB, STATUS, STOLIKI_ID_STOLIKA)
VALUES(1, 10,'2024-12-12', '15:21', 5, 'Zaakceptowana', 1);

INSERT INTO REZERWACJE(ID_REZERWACJI, ID_KLIENTA, DATA_REZERWACJI, GODZINA, ILOŒÆ_OSÓB, STATUS, STOLIKI_ID_STOLIKA)
VALUES(2, 11,'2024-12-11', '16:43', 6, 'Zaakceptowana', 2);

INSERT INTO REZERWACJE(ID_REZERWACJI, ID_KLIENTA, DATA_REZERWACJI, GODZINA, ILOŒÆ_OSÓB, STATUS, STOLIKI_ID_STOLIKA)
VALUES(3, 12,'2022-11-12', '17:18', 4, 'Zaakceptowana', 3);

INSERT INTO REZERWACJE(ID_REZERWACJI, ID_KLIENTA, DATA_REZERWACJI, GODZINA, ILOŒÆ_OSÓB, STATUS, STOLIKI_ID_STOLIKA)
VALUES(4, 13,'2023-10-12', '20:12', 5, 'Zaakceptowana', 4);

INSERT INTO REZERWACJE(ID_REZERWACJI, ID_KLIENTA, DATA_REZERWACJI, GODZINA, ILOŒÆ_OSÓB, STATUS, STOLIKI_ID_STOLIKA)
VALUES(5, 14,'2021-12-12', '17:50', 3, 'Zaakceptowana', 5);

--SK£ADNIKI---------------------
INSERT INTO SK£ADNIKI(ID_SK£ADNIKA, NAZWA, GRAMATURA, DOSTAWCY_ID_DOSTAWCY, DANIE_ID_DANIA)
VALUES(15, 'POMIDOR', 3, 1, 2);

INSERT INTO SK£ADNIKI(ID_SK£ADNIKA, NAZWA, GRAMATURA, DOSTAWCY_ID_DOSTAWCY, DANIE_ID_DANIA)
VALUES(16, 'KURCZAK', 4, 2, 1);

INSERT INTO SK£ADNIKI(ID_SK£ADNIKA, NAZWA, GRAMATURA, DOSTAWCY_ID_DOSTAWCY, DANIE_ID_DANIA)
VALUES(17, 'SCHAB', 5, 3, 3);

INSERT INTO SK£ADNIKI(ID_SK£ADNIKA, NAZWA, GRAMATURA, DOSTAWCY_ID_DOSTAWCY, DANIE_ID_DANIA)
VALUES(18, 'M¥KA', 10, 4, 4);

INSERT INTO SK£ADNIKI(ID_SK£ADNIKA, NAZWA, GRAMATURA, DOSTAWCY_ID_DOSTAWCY, DANIE_ID_DANIA)
VALUES(19, 'ZIEMNIAKI', 20, 5, 5);


--STOLIKI------------------------
INSERT INTO STOLIKI(ID_STOLIKA, NUMER_STOLIKA, LICZBA_MIEJSC, STATUS, RACHUNKI_ID_RACHUNKU)
VALUES(1, 1, 4, 'ZAREZERWOWANY', 1);

INSERT INTO STOLIKI(ID_STOLIKA, NUMER_STOLIKA, LICZBA_MIEJSC, STATUS, RACHUNKI_ID_RACHUNKU)
VALUES(2, 2, 3, 'ZAREZERWOWANY', 2);

INSERT INTO STOLIKI(ID_STOLIKA, NUMER_STOLIKA, LICZBA_MIEJSC, STATUS, RACHUNKI_ID_RACHUNKU)
VALUES(3, 3, 6, 'WOLNY', 3);

INSERT INTO STOLIKI(ID_STOLIKA, NUMER_STOLIKA, LICZBA_MIEJSC, STATUS, RACHUNKI_ID_RACHUNKU)
VALUES(4, 4, 2, 'ZAREZERWOWANY', 4);

INSERT INTO STOLIKI(ID_STOLIKA, NUMER_STOLIKA, LICZBA_MIEJSC, STATUS, RACHUNKI_ID_RACHUNKU)
VALUES(5, 5, 4, 'WOLNY', 5);

DROP TABLE DEPARTMENTS;
DROP TABLE EMPLOYEES;
DROP TABLE JOB_GRADES;
DROP TABLE POSITIONS;
DROP TABLE WORKERS;
COMMIT;

-- 1 przypadek u¿ycia bazy danych -------> Grupowanie
CREATE VIEW perspektywa_1 AS
SELECT METODA_P£ATNOŒCI, SUM(KWOTA) AS SUMA_KWOTA
FROM P£ATNOŒCI
GROUP BY METODA_P£ATNOŒCI;

-- 2 przypadek u¿ycia bazy danych -----> Sortowanie
CREATE VIEW perspektywa_2 AS
SELECT NAZWA_DANIA, CENA, DOSTÊPNOŒÆ
FROM DANIE
ORDER BY CENA ASC;

--3 przypadek u¿ycia bazy danych -----> £¹czenie 3 tabel
CREATE OR REPLACE VIEW perspektywa_3 AS
SELECT p.KWOTA, p.METODA_P£ATNOŒCI,r.status,r.id_klienta, re.iloœæ_osób,re.stoliki_id_stolika as id_stolika, s.NUMER_STOLIKA
FROM P³ATNOŒCI p
JOIN RACHUNKI r
ON(p.DATA_P£ATNOŒCI = r.DATA_ZAMÓWIENIA)
    JOIN REZERWACJE re
ON(p.DATA_P£ATNOŒCI = re.DATA_REZERWACJI)
    JOIN STOLIKI s
ON(re.STOLIKI_ID_STOLIKA = s.ID_STOLIKA);


--4 przypadek u¿ycia bazy danych------------------------------------------------
---Nieskorelowane

CREATE VIEW perspektywa_4 AS
SELECT NAZWA_DANIA
FROM DANIE
WHERE CENA >(SELECT CENA
            FROM DANIE
            WHERE ID_DANIA = 5);

---Skorelowane

CREATE VIEW perspektywa_5 AS
SELECT NAZWA_DANIA
FROM DANIE
WHERE CENA >(SELECT AVG(CENA)
            FROM DANIE);
--5 przypadek u¿ycia bazy danych ---->JEDNOWIERSZOWE

CREATE VIEW perspektywa_6 AS
SELECT ID_RACHUNKU, ID_KLIENTA, STATUS, TO_CHAR(DATA_ZAMÓWIENIA, 'YYYY/Mon/DD') AS DATA
FROM RACHUNKI
WHERE DATA_ZAMÓWIENIA < TO_DATE('2024/12/31', 'YYYY/MM/DD');

--GRUPOWA
CREATE OR REPLACE VIEW perspektywa_7 AS
SELECT MAX(CENA) AS NAJDROZSZE, MIN(CENA) AS NAJTANSZE, AVG(CENA) AS SREDNIA, SUM(cena) AS SUMA_CEN_DAN
FROM DANIE;

CREATE VIEW perspektywa_8 AS
SELECT NVL(TELEFON, 0) AS NUMER_LUB_ZERO
FROM KLIENCI;

CREATE OR REPLACE VIEW perspektywa_9 AS
SELECT UPPER(STATUS) AS CAPS
FROM REZERWACJE;

CREATE VIEW perspektywa_10 AS
SELECT ROUND(AVG(KWOTA), 2) AS ŒREDNIA_P£ATNOŒÆ
FROM P£ATNOŒCI;

---Sekwencery------------------------------------------------------------------
CREATE SEQUENCE id_samochodu_seq
INCREMENT BY 1
START WITH 1
MAXVALUE 50
NOCACHE
NOCYCLE;

DROP SEQUENCE id_samochodu_seq;

ALTER TABLE DOSTAWCY
ADD id_samochodu NUMERIC(2);

INSERT INTO DOSTAWCY(ID_DOSTAWCY, IMIÊ, NAZWISKO, TELEFON, NUMER_REJESTRACYJNY_SAMOCHODU, KIEROWNIK_ID_KIEROWNIKA, id_samochodu)
VALUES(6, 'HENRYK', 'JAD£OMISTRZ', 987654321, 'PO87654', 1, id_samochodu_seq.NEXTVAL);

UPDATE DOSTAWCY
SET ID_SAMOCHODU = id_samochodu_seq.NEXTVAL
WHERE ID_DOSTAWCY = 6;
UPDATE DOSTAWCY
SET ID_SAMOCHODU = id_samochodu_seq.NEXTVAL
WHERE ID_DOSTAWCY = 1;
UPDATE DOSTAWCY
SET ID_SAMOCHODU = id_samochodu_seq.NEXTVAL
WHERE ID_DOSTAWCY = 2;
UPDATE DOSTAWCY
SET ID_SAMOCHODU = id_samochodu_seq.NEXTVAL
WHERE ID_DOSTAWCY = 3;
UPDATE DOSTAWCY
SET ID_SAMOCHODU = id_samochodu_seq.NEXTVAL
WHERE ID_DOSTAWCY = 4;
UPDATE DOSTAWCY
SET ID_SAMOCHODU = id_samochodu_seq.NEXTVAL
WHERE ID_DOSTAWCY = 5;

---DRUGI SEKWENCER--------------------------------------------------------------
CREATE SEQUENCE numer_koszulki_seq
INCREMENT BY 1
START WITH 22
MAXVALUE 50
NOCACHE
NOCYCLE;

ALTER TABLE PRACOWNICY
ADD numer_koszulki_pilkarskiej NUMERIC(2);

ALTER TABLE PRACOWNICY
DROP COLUMN numer_koszulki;

UPDATE PRACOWNICY
SET numer_koszulki_pilkarskiej = numer_koszulki_seq.NEXTVAL
WHERE ID_PRACOWNIKA = 30;
UPDATE PRACOWNICY
SET numer_koszulki_pilkarskiej = numer_koszulki_seq.NEXTVAL
WHERE ID_PRACOWNIKA = 31;
UPDATE PRACOWNICY
SET numer_koszulki_pilkarskiej = numer_koszulki_seq.NEXTVAL
WHERE ID_PRACOWNIKA = 32;
UPDATE PRACOWNICY
SET numer_koszulki_pilkarskiej = numer_koszulki_seq.NEXTVAL
WHERE ID_PRACOWNIKA = 33;
UPDATE PRACOWNICY
SET numer_koszulki_pilkarskiej = numer_koszulki_seq.NEXTVAL
WHERE ID_PRACOWNIKA = 34;