--------------------------------------------------------
--  File created - wtorek-stycznia-28-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ID_SAMOCHODU_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "IE88244"."ID_SAMOCHODU_SEQ"  MINVALUE 1 MAXVALUE 50 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence NUMER_KOSZULKI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "IE88244"."NUMER_KOSZULKI_SEQ"  MINVALUE 1 MAXVALUE 50 INCREMENT BY 1 START WITH 28 NOCACHE  NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Table DANIE
--------------------------------------------------------

  CREATE TABLE "IE88244"."DANIE" 
   (	"ID_DANIA" NUMBER, 
	"NAZWA_DANIA" VARCHAR2(20 BYTE), 
	"OPIS" VARCHAR2(20 BYTE), 
	"CENA" VARCHAR2(20 BYTE), 
	"DOSTÊPNOŒÆ" VARCHAR2(20 BYTE), 
	"PRODUKTY" VARCHAR2(20 BYTE), 
	"MENU_ID_MENU" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DOSTAWCY
--------------------------------------------------------

  CREATE TABLE "IE88244"."DOSTAWCY" 
   (	"ID_DOSTAWCY" NUMBER, 
	"IMIÊ" VARCHAR2(20 BYTE), 
	"NAZWISKO" VARCHAR2(20 BYTE), 
	"TELEFON" NUMBER(9,0), 
	"NUMER_REJESTRACYJNY_SAMOCHODU" VARCHAR2(15 BYTE), 
	"KIEROWNIK_ID_KIEROWNIKA" NUMBER, 
	"ID_SAMOCHODU" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KIEROWNIK
--------------------------------------------------------

  CREATE TABLE "IE88244"."KIEROWNIK" 
   (	"ID_KIEROWNIKA" NUMBER, 
	"IMIÊ" VARCHAR2(20 BYTE), 
	"NAZWISKO" VARCHAR2(20 BYTE), 
	"TELEFON" NUMBER(9,0), 
	"PESEL" NUMBER(11,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KLIENCI
--------------------------------------------------------

  CREATE TABLE "IE88244"."KLIENCI" 
   (	"ID_KLIENTA" NUMBER, 
	"IMIÊ" VARCHAR2(20 BYTE), 
	"NAZWISKO" VARCHAR2(20 BYTE), 
	"TELEFON" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MENU
--------------------------------------------------------

  CREATE TABLE "IE88244"."MENU" 
   (	"ID_MENU" NUMBER, 
	"LISTA_DAÑ" VARCHAR2(60 BYTE), 
	"DATA_AKTUALIZACJI" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table P£ATNOŒCI
--------------------------------------------------------

  CREATE TABLE "IE88244"."P£ATNOŒCI" 
   (	"ID_P£ATNOŒCI" NUMBER, 
	"DATA_P£ATNOŒCI" DATE, 
	"GODZINA" VARCHAR2(60 BYTE), 
	"KWOTA" NUMBER, 
	"METODA_P£ATNOŒCI" VARCHAR2(20 BYTE), 
	"RACHUNKI_ID_RACHUNKU" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRACOWNICY
--------------------------------------------------------

  CREATE TABLE "IE88244"."PRACOWNICY" 
   (	"ID_PRACOWNIKA" NUMBER, 
	"IMIÊ" VARCHAR2(20 BYTE), 
	"NAZWISKO" VARCHAR2(20 BYTE), 
	"ROLA" VARCHAR2(20 BYTE), 
	"TELEFON" NUMBER(9,0), 
	"PESEL" NUMBER(11,0), 
	"KIEROWNIK_ID_KIEROWNIKA" NUMBER, 
	"NUMER_KOSZULKI_PILKARSKIEJ" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RACHUNKI
--------------------------------------------------------

  CREATE TABLE "IE88244"."RACHUNKI" 
   (	"ID_RACHUNKU" NUMBER, 
	"ID_KLIENTA" NUMBER, 
	"DATA_ZAMÓWIENIA" DATE, 
	"GODZINA" VARCHAR2(10 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"PRACOWNICY_ID_PRACOWNIKA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RELATION_1
--------------------------------------------------------

  CREATE TABLE "IE88244"."RELATION_1" 
   (	"KLIENCI_ID_KLIENTA" NUMBER, 
	"REZERWACJE_ID_REZERWACJI" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REZERWACJE
--------------------------------------------------------

  CREATE TABLE "IE88244"."REZERWACJE" 
   (	"ID_REZERWACJI" NUMBER, 
	"ID_KLIENTA" NUMBER, 
	"DATA_REZERWACJI" DATE, 
	"GODZINA" VARCHAR2(10 BYTE), 
	"ILOŒÆ_OSÓB" NUMBER(*,0), 
	"STATUS" VARCHAR2(20 BYTE), 
	"STOLIKI_ID_STOLIKA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SK£ADNIKI
--------------------------------------------------------

  CREATE TABLE "IE88244"."SK£ADNIKI" 
   (	"ID_SK£ADNIKA" VARCHAR2(20 BYTE), 
	"NAZWA" VARCHAR2(20 BYTE), 
	"GRAMATURA" FLOAT(126), 
	"DOSTAWCY_ID_DOSTAWCY" NUMBER, 
	"DANIE_ID_DANIA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STOLIKI
--------------------------------------------------------

  CREATE TABLE "IE88244"."STOLIKI" 
   (	"ID_STOLIKA" NUMBER, 
	"NUMER_STOLIKA" VARCHAR2(20 BYTE), 
	"LICZBA_MIEJSC" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"RACHUNKI_ID_RACHUNKU" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for View PERSPEKTYWA_1
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "IE88244"."PERSPEKTYWA_1" ("METODA_P£ATNOŒCI", "SUMA_KWOTA") AS 
  SELECT METODA_P£ATNOŒCI, SUM(KWOTA) AS SUMA_KWOTA
FROM P£ATNOŒCI
GROUP BY METODA_P£ATNOŒCI
;
--------------------------------------------------------
--  DDL for View PERSPEKTYWA_10
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "IE88244"."PERSPEKTYWA_10" ("ŒREDNIA_P£ATNOŒÆ") AS 
  SELECT ROUND(AVG(KWOTA), 2) AS ŒREDNIA_P£ATNOŒÆ
FROM P£ATNOŒCI
;
--------------------------------------------------------
--  DDL for View PERSPEKTYWA_2
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "IE88244"."PERSPEKTYWA_2" ("NAZWA_DANIA", "CENA", "DOSTÊPNOŒÆ") AS 
  SELECT NAZWA_DANIA, CENA, DOSTÊPNOŒÆ
FROM DANIE
ORDER BY CENA ASC
;
--------------------------------------------------------
--  DDL for View PERSPEKTYWA_3
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "IE88244"."PERSPEKTYWA_3" ("KWOTA", "METODA_P£ATNOŒCI", "STATUS", "ID_KLIENTA", "ILOŒÆ_OSÓB", "ID_STOLIKA", "NUMER_STOLIKA") AS 
  SELECT p.KWOTA, p.METODA_P£ATNOŒCI,r.status,r.id_klienta, re.iloœæ_osób,re.stoliki_id_stolika as id_stolika, s.NUMER_STOLIKA
FROM P³ATNOŒCI p
JOIN RACHUNKI r
ON(p.DATA_P£ATNOŒCI = r.DATA_ZAMÓWIENIA)
    JOIN REZERWACJE re
ON(p.DATA_P£ATNOŒCI = re.DATA_REZERWACJI)
    JOIN STOLIKI s
ON(re.STOLIKI_ID_STOLIKA = s.ID_STOLIKA)
;
--------------------------------------------------------
--  DDL for View PERSPEKTYWA_4
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "IE88244"."PERSPEKTYWA_4" ("NAZWA_DANIA") AS 
  SELECT NAZWA_DANIA
FROM DANIE
WHERE CENA >(SELECT CENA
            FROM DANIE
            WHERE ID_DANIA = 5)
;
--------------------------------------------------------
--  DDL for View PERSPEKTYWA_5
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "IE88244"."PERSPEKTYWA_5" ("NAZWA_DANIA") AS 
  SELECT NAZWA_DANIA
FROM DANIE
WHERE CENA >(SELECT AVG(CENA)
            FROM DANIE)
;
--------------------------------------------------------
--  DDL for View PERSPEKTYWA_6
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "IE88244"."PERSPEKTYWA_6" ("ID_RACHUNKU", "ID_KLIENTA", "STATUS", "DATA") AS 
  SELECT ID_RACHUNKU, ID_KLIENTA, STATUS, TO_CHAR(DATA_ZAMÓWIENIA, 'YYYY/Mon/DD') AS DATA
FROM RACHUNKI
WHERE DATA_ZAMÓWIENIA < TO_DATE('2024/12/31', 'YYYY/MM/DD')
;
--------------------------------------------------------
--  DDL for View PERSPEKTYWA_7
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "IE88244"."PERSPEKTYWA_7" ("NAJDROZSZE", "NAJTANSZE", "SREDNIA", "SUMA_CEN_DAN") AS 
  SELECT MAX(CENA) AS NAJDROZSZE, MIN(CENA) AS NAJTANSZE, AVG(CENA) AS SREDNIA, SUM(cena) AS SUMA_CEN_DAN
FROM DANIE
;
--------------------------------------------------------
--  DDL for View PERSPEKTYWA_8
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "IE88244"."PERSPEKTYWA_8" ("NUMER_LUB_ZERO") AS 
  SELECT NVL(TELEFON, 0) AS NUMER_LUB_ZERO
FROM KLIENCI
;
--------------------------------------------------------
--  DDL for View PERSPEKTYWA_9
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "IE88244"."PERSPEKTYWA_9" ("CAPS") AS 
  SELECT UPPER(STATUS) AS CAPS
FROM REZERWACJE
;
REM INSERTING into IE88244.DANIE
SET DEFINE OFF;
Insert into IE88244.DANIE (ID_DANIA,NAZWA_DANIA,OPIS,CENA,"DOSTÊPNOŒÆ",PRODUKTY,MENU_ID_MENU) values ('1','ROSÓ£','ZUPA Z KURY','15','ZAWSZE','BULION, MAKARON','1');
Insert into IE88244.DANIE (ID_DANIA,NAZWA_DANIA,OPIS,CENA,"DOSTÊPNOŒÆ",PRODUKTY,MENU_ID_MENU) values ('2','POMODORO','ZUPA Z POMIDORA','15','ZAWSZE','BULION, POMODORO','1');
Insert into IE88244.DANIE (ID_DANIA,NAZWA_DANIA,OPIS,CENA,"DOSTÊPNOŒÆ",PRODUKTY,MENU_ID_MENU) values ('5','FRYTKI','ZIEMNIAKI/BATATY','20','ZAWSZE','ZIEMNIAKI, KECZUP','1');
Insert into IE88244.DANIE (ID_DANIA,NAZWA_DANIA,OPIS,CENA,"DOSTÊPNOŒÆ",PRODUKTY,MENU_ID_MENU) values ('4','PIEROGSY','PIEROGI Z MIÊSEM','28','SPYTAJ KELNERA','CIASTO, MIÊSO','1');
Insert into IE88244.DANIE (ID_DANIA,NAZWA_DANIA,OPIS,CENA,"DOSTÊPNOŒÆ",PRODUKTY,MENU_ID_MENU) values ('3','SCHABOSZCZAK','MIÊSO ZE ŒWINI','33','ZAWSZE','SCHAB, ZIEMNIAKI','1');
REM INSERTING into IE88244.DOSTAWCY
SET DEFINE OFF;
Insert into IE88244.DOSTAWCY (ID_DOSTAWCY,"IMIÊ",NAZWISKO,TELEFON,NUMER_REJESTRACYJNY_SAMOCHODU,KIEROWNIK_ID_KIEROWNIKA,ID_SAMOCHODU) values ('6','HENRYK','JAD£OMISTRZ','987654321','PO87654','1','13');
Insert into IE88244.DOSTAWCY (ID_DOSTAWCY,"IMIÊ",NAZWISKO,TELEFON,NUMER_REJESTRACYJNY_SAMOCHODU,KIEROWNIK_ID_KIEROWNIKA,ID_SAMOCHODU) values ('1','JANUSZ','MA£YSZ','555555555','PO10001','1','8');
Insert into IE88244.DOSTAWCY (ID_DOSTAWCY,"IMIÊ",NAZWISKO,TELEFON,NUMER_REJESTRACYJNY_SAMOCHODU,KIEROWNIK_ID_KIEROWNIKA,ID_SAMOCHODU) values ('2','BART£OMIEJ','GA£¥ZKA','837428283','PO12340','1','9');
Insert into IE88244.DOSTAWCY (ID_DOSTAWCY,"IMIÊ",NAZWISKO,TELEFON,NUMER_REJESTRACYJNY_SAMOCHODU,KIEROWNIK_ID_KIEROWNIKA,ID_SAMOCHODU) values ('3','IGOR','POZNAÑSKI','666666666','PO54671','1','10');
Insert into IE88244.DOSTAWCY (ID_DOSTAWCY,"IMIÊ",NAZWISKO,TELEFON,NUMER_REJESTRACYJNY_SAMOCHODU,KIEROWNIK_ID_KIEROWNIKA,ID_SAMOCHODU) values ('4','BARTOSZ','MA£OMIEJSKI','198765432','PO18201','1','11');
Insert into IE88244.DOSTAWCY (ID_DOSTAWCY,"IMIÊ",NAZWISKO,TELEFON,NUMER_REJESTRACYJNY_SAMOCHODU,KIEROWNIK_ID_KIEROWNIKA,ID_SAMOCHODU) values ('5','MARCELI','TORUÑSKI','571885555','PO25001','1','12');
REM INSERTING into IE88244.KIEROWNIK
SET DEFINE OFF;
Insert into IE88244.KIEROWNIK (ID_KIEROWNIKA,"IMIÊ",NAZWISKO,TELEFON,PESEL) values ('1','AREK','LODO£AMACZ','123123123','12345678911');
REM INSERTING into IE88244.KLIENCI
SET DEFINE OFF;
Insert into IE88244.KLIENCI (ID_KLIENTA,"IMIÊ",NAZWISKO,TELEFON) values ('10','EDYTA','NEKIELSKA','987098456');
Insert into IE88244.KLIENCI (ID_KLIENTA,"IMIÊ",NAZWISKO,TELEFON) values ('11','JULITA','TAKA','765123123');
Insert into IE88244.KLIENCI (ID_KLIENTA,"IMIÊ",NAZWISKO,TELEFON) values ('12','MAGDA','JAKA','358456654');
Insert into IE88244.KLIENCI (ID_KLIENTA,"IMIÊ",NAZWISKO,TELEFON) values ('13','KLAUDIA','BAROWA','234432234');
Insert into IE88244.KLIENCI (ID_KLIENTA,"IMIÊ",NAZWISKO,TELEFON) values ('14','OLENA','KRAKOWSKA','876876123');
REM INSERTING into IE88244.MENU
SET DEFINE OFF;
Insert into IE88244.MENU (ID_MENU,"LISTA_DAÑ",DATA_AKTUALIZACJI) values ('1','ROSÓ£, POMIDORO, FRYTKI, PIEROGSY, SCHABOSZCZAK','2021-01-05');
REM INSERTING into IE88244."P£ATNOŒCI"
SET DEFINE OFF;
Insert into IE88244."P£ATNOŒCI" ("ID_P£ATNOŒCI","DATA_P£ATNOŒCI",GODZINA,KWOTA,"METODA_P£ATNOŒCI",RACHUNKI_ID_RACHUNKU) values ('1',to_date('24/12/12','RR/MM/DD'),'15:21','65','KARTA','1');
Insert into IE88244."P£ATNOŒCI" ("ID_P£ATNOŒCI","DATA_P£ATNOŒCI",GODZINA,KWOTA,"METODA_P£ATNOŒCI",RACHUNKI_ID_RACHUNKU) values ('2',to_date('24/12/11','RR/MM/DD'),'16:43','106','KARTA','2');
Insert into IE88244."P£ATNOŒCI" ("ID_P£ATNOŒCI","DATA_P£ATNOŒCI",GODZINA,KWOTA,"METODA_P£ATNOŒCI",RACHUNKI_ID_RACHUNKU) values ('3',to_date('22/11/12','RR/MM/DD'),'17:18','122','GOTÓWKA','3');
Insert into IE88244."P£ATNOŒCI" ("ID_P£ATNOŒCI","DATA_P£ATNOŒCI",GODZINA,KWOTA,"METODA_P£ATNOŒCI",RACHUNKI_ID_RACHUNKU) values ('4',to_date('23/10/12','RR/MM/DD'),'20:12','45','KARTA','4');
Insert into IE88244."P£ATNOŒCI" ("ID_P£ATNOŒCI","DATA_P£ATNOŒCI",GODZINA,KWOTA,"METODA_P£ATNOŒCI",RACHUNKI_ID_RACHUNKU) values ('5',to_date('21/12/12','RR/MM/DD'),'17:50','187','GOTÓWKA','5');
REM INSERTING into IE88244.PRACOWNICY
SET DEFINE OFF;
Insert into IE88244.PRACOWNICY (ID_PRACOWNIKA,"IMIÊ",NAZWISKO,ROLA,TELEFON,PESEL,KIEROWNIK_ID_KIEROWNIKA,NUMER_KOSZULKI_PILKARSKIEJ) values ('30','EDYTA','KONIECZNA','KELNER','432456789','90987667843','1','22');
Insert into IE88244.PRACOWNICY (ID_PRACOWNIKA,"IMIÊ",NAZWISKO,ROLA,TELEFON,PESEL,KIEROWNIK_ID_KIEROWNIKA,NUMER_KOSZULKI_PILKARSKIEJ) values ('31','ANTONI','KOSIBA','KELNER','929615473','98712345672','1','23');
Insert into IE88244.PRACOWNICY (ID_PRACOWNIKA,"IMIÊ",NAZWISKO,ROLA,TELEFON,PESEL,KIEROWNIK_ID_KIEROWNIKA,NUMER_KOSZULKI_PILKARSKIEJ) values ('32','ANNA','WESO£OWSKA','KELNER','967567432','99887766554','1','24');
Insert into IE88244.PRACOWNICY (ID_PRACOWNIKA,"IMIÊ",NAZWISKO,ROLA,TELEFON,PESEL,KIEROWNIK_ID_KIEROWNIKA,NUMER_KOSZULKI_PILKARSKIEJ) values ('33','MAKSYMILIAN','£AKOMY','BARMAN','787454323','99007744345','1','25');
Insert into IE88244.PRACOWNICY (ID_PRACOWNIKA,"IMIÊ",NAZWISKO,ROLA,TELEFON,PESEL,KIEROWNIK_ID_KIEROWNIKA,NUMER_KOSZULKI_PILKARSKIEJ) values ('34','JAKUB','NIEPEWNY','RECEPCJONISTA','919282545','98767854321','1','27');
REM INSERTING into IE88244.RACHUNKI
SET DEFINE OFF;
Insert into IE88244.RACHUNKI (ID_RACHUNKU,ID_KLIENTA,"DATA_ZAMÓWIENIA",GODZINA,STATUS,PRACOWNICY_ID_PRACOWNIKA) values ('1','10',to_date('24/12/12','RR/MM/DD'),'12:00','OP£ACONE','30');
Insert into IE88244.RACHUNKI (ID_RACHUNKU,ID_KLIENTA,"DATA_ZAMÓWIENIA",GODZINA,STATUS,PRACOWNICY_ID_PRACOWNIKA) values ('2','11',to_date('24/12/11','RR/MM/DD'),'12:30','OP£ACONE','31');
Insert into IE88244.RACHUNKI (ID_RACHUNKU,ID_KLIENTA,"DATA_ZAMÓWIENIA",GODZINA,STATUS,PRACOWNICY_ID_PRACOWNIKA) values ('3','12',to_date('22/11/12','RR/MM/DD'),'13:00','OP£ACONE','32');
Insert into IE88244.RACHUNKI (ID_RACHUNKU,ID_KLIENTA,"DATA_ZAMÓWIENIA",GODZINA,STATUS,PRACOWNICY_ID_PRACOWNIKA) values ('4','13',to_date('23/10/12','RR/MM/DD'),'12:00','OP£ACONE','33');
Insert into IE88244.RACHUNKI (ID_RACHUNKU,ID_KLIENTA,"DATA_ZAMÓWIENIA",GODZINA,STATUS,PRACOWNICY_ID_PRACOWNIKA) values ('5','14',to_date('21/12/12','RR/MM/DD'),'14:00','OP£ACONE','34');
REM INSERTING into IE88244.RELATION_1
SET DEFINE OFF;
REM INSERTING into IE88244.REZERWACJE
SET DEFINE OFF;
Insert into IE88244.REZERWACJE (ID_REZERWACJI,ID_KLIENTA,DATA_REZERWACJI,GODZINA,"ILOŒÆ_OSÓB",STATUS,STOLIKI_ID_STOLIKA) values ('1','10',to_date('24/12/12','RR/MM/DD'),'15:21','5','Zaakceptowana','1');
Insert into IE88244.REZERWACJE (ID_REZERWACJI,ID_KLIENTA,DATA_REZERWACJI,GODZINA,"ILOŒÆ_OSÓB",STATUS,STOLIKI_ID_STOLIKA) values ('2','11',to_date('24/12/11','RR/MM/DD'),'16:43','6','Zaakceptowana','2');
Insert into IE88244.REZERWACJE (ID_REZERWACJI,ID_KLIENTA,DATA_REZERWACJI,GODZINA,"ILOŒÆ_OSÓB",STATUS,STOLIKI_ID_STOLIKA) values ('3','12',to_date('22/11/12','RR/MM/DD'),'17:18','4','Zaakceptowana','3');
Insert into IE88244.REZERWACJE (ID_REZERWACJI,ID_KLIENTA,DATA_REZERWACJI,GODZINA,"ILOŒÆ_OSÓB",STATUS,STOLIKI_ID_STOLIKA) values ('4','13',to_date('23/10/12','RR/MM/DD'),'20:12','5','Zaakceptowana','4');
Insert into IE88244.REZERWACJE (ID_REZERWACJI,ID_KLIENTA,DATA_REZERWACJI,GODZINA,"ILOŒÆ_OSÓB",STATUS,STOLIKI_ID_STOLIKA) values ('5','14',to_date('21/12/12','RR/MM/DD'),'17:50','3','Zaakceptowana','5');
REM INSERTING into IE88244."SK£ADNIKI"
SET DEFINE OFF;
Insert into IE88244."SK£ADNIKI" ("ID_SK£ADNIKA",NAZWA,GRAMATURA,DOSTAWCY_ID_DOSTAWCY,DANIE_ID_DANIA) values ('15','POMIDOR','3','1','2');
Insert into IE88244."SK£ADNIKI" ("ID_SK£ADNIKA",NAZWA,GRAMATURA,DOSTAWCY_ID_DOSTAWCY,DANIE_ID_DANIA) values ('16','KURCZAK','4','2','1');
Insert into IE88244."SK£ADNIKI" ("ID_SK£ADNIKA",NAZWA,GRAMATURA,DOSTAWCY_ID_DOSTAWCY,DANIE_ID_DANIA) values ('17','SCHAB','5','3','3');
Insert into IE88244."SK£ADNIKI" ("ID_SK£ADNIKA",NAZWA,GRAMATURA,DOSTAWCY_ID_DOSTAWCY,DANIE_ID_DANIA) values ('18','M¥KA','10','4','4');
Insert into IE88244."SK£ADNIKI" ("ID_SK£ADNIKA",NAZWA,GRAMATURA,DOSTAWCY_ID_DOSTAWCY,DANIE_ID_DANIA) values ('19','ZIEMNIAKI','20','5','5');
REM INSERTING into IE88244.STOLIKI
SET DEFINE OFF;
Insert into IE88244.STOLIKI (ID_STOLIKA,NUMER_STOLIKA,LICZBA_MIEJSC,STATUS,RACHUNKI_ID_RACHUNKU) values ('1','1','4','ZAREZERWOWANY','1');
Insert into IE88244.STOLIKI (ID_STOLIKA,NUMER_STOLIKA,LICZBA_MIEJSC,STATUS,RACHUNKI_ID_RACHUNKU) values ('2','2','3','ZAREZERWOWANY','2');
Insert into IE88244.STOLIKI (ID_STOLIKA,NUMER_STOLIKA,LICZBA_MIEJSC,STATUS,RACHUNKI_ID_RACHUNKU) values ('3','3','6','WOLNY','3');
Insert into IE88244.STOLIKI (ID_STOLIKA,NUMER_STOLIKA,LICZBA_MIEJSC,STATUS,RACHUNKI_ID_RACHUNKU) values ('4','4','2','ZAREZERWOWANY','4');
Insert into IE88244.STOLIKI (ID_STOLIKA,NUMER_STOLIKA,LICZBA_MIEJSC,STATUS,RACHUNKI_ID_RACHUNKU) values ('5','5','4','WOLNY','5');
--------------------------------------------------------
--  DDL for Index KLIENCI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IE88244"."KLIENCI_PK" ON "IE88244"."KLIENCI" ("ID_KLIENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index P£ATNOŒCI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IE88244"."P£ATNOŒCI_PK" ON "IE88244"."P£ATNOŒCI" ("ID_P£ATNOŒCI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DANIE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IE88244"."DANIE_PK" ON "IE88244"."DANIE" ("ID_DANIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STOLIKI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IE88244"."STOLIKI_PK" ON "IE88244"."STOLIKI" ("ID_STOLIKA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RELATION_1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IE88244"."RELATION_1_PK" ON "IE88244"."RELATION_1" ("KLIENCI_ID_KLIENTA", "REZERWACJE_ID_REZERWACJI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KIEROWNIK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IE88244"."KIEROWNIK_PK" ON "IE88244"."KIEROWNIK" ("ID_KIEROWNIKA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MENU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IE88244"."MENU_PK" ON "IE88244"."MENU" ("ID_MENU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STOLIKI__IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "IE88244"."STOLIKI__IDX" ON "IE88244"."STOLIKI" ("RACHUNKI_ID_RACHUNKU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index P£ATNOŒCI__IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "IE88244"."P£ATNOŒCI__IDX" ON "IE88244"."P£ATNOŒCI" ("RACHUNKI_ID_RACHUNKU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRACOWNICY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IE88244"."PRACOWNICY_PK" ON "IE88244"."PRACOWNICY" ("ID_PRACOWNIKA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RACHUNKI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IE88244"."RACHUNKI_PK" ON "IE88244"."RACHUNKI" ("ID_RACHUNKU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DOSTAWCY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IE88244"."DOSTAWCY_PK" ON "IE88244"."DOSTAWCY" ("ID_DOSTAWCY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SK£ADNIKI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IE88244"."SK£ADNIKI_PK" ON "IE88244"."SK£ADNIKI" ("ID_SK£ADNIKA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REZERWACJE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IE88244"."REZERWACJE_PK" ON "IE88244"."REZERWACJE" ("ID_REZERWACJI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table REZERWACJE
--------------------------------------------------------

  ALTER TABLE "IE88244"."REZERWACJE" ADD CONSTRAINT "REZERWACJE_PK" PRIMARY KEY ("ID_REZERWACJI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IE88244"."REZERWACJE" MODIFY ("ID_REZERWACJI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "IE88244"."MENU" ADD CONSTRAINT "MENU_PK" PRIMARY KEY ("ID_MENU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IE88244"."MENU" MODIFY ("ID_MENU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KLIENCI
--------------------------------------------------------

  ALTER TABLE "IE88244"."KLIENCI" ADD CONSTRAINT "KLIENCI_PK" PRIMARY KEY ("ID_KLIENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IE88244"."KLIENCI" MODIFY ("ID_KLIENTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KIEROWNIK
--------------------------------------------------------

  ALTER TABLE "IE88244"."KIEROWNIK" ADD CONSTRAINT "KIEROWNIK_PK" PRIMARY KEY ("ID_KIEROWNIKA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IE88244"."KIEROWNIK" MODIFY ("ID_KIEROWNIKA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RACHUNKI
--------------------------------------------------------

  ALTER TABLE "IE88244"."RACHUNKI" ADD CONSTRAINT "RACHUNKI_PK" PRIMARY KEY ("ID_RACHUNKU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IE88244"."RACHUNKI" MODIFY ("ID_RACHUNKU" NOT NULL ENABLE);
  ALTER TABLE "IE88244"."RACHUNKI" MODIFY ("PRACOWNICY_ID_PRACOWNIKA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SK£ADNIKI
--------------------------------------------------------

  ALTER TABLE "IE88244"."SK£ADNIKI" ADD CONSTRAINT "SK£ADNIKI_PK" PRIMARY KEY ("ID_SK£ADNIKA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IE88244"."SK£ADNIKI" MODIFY ("ID_SK£ADNIKA" NOT NULL ENABLE);
  ALTER TABLE "IE88244"."SK£ADNIKI" MODIFY ("DOSTAWCY_ID_DOSTAWCY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STOLIKI
--------------------------------------------------------

  ALTER TABLE "IE88244"."STOLIKI" ADD CONSTRAINT "STOLIKI_PK" PRIMARY KEY ("ID_STOLIKA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IE88244"."STOLIKI" MODIFY ("ID_STOLIKA" NOT NULL ENABLE);
  ALTER TABLE "IE88244"."STOLIKI" MODIFY ("RACHUNKI_ID_RACHUNKU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRACOWNICY
--------------------------------------------------------

  ALTER TABLE "IE88244"."PRACOWNICY" ADD CONSTRAINT "PRACOWNICY_PK" PRIMARY KEY ("ID_PRACOWNIKA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IE88244"."PRACOWNICY" MODIFY ("ID_PRACOWNIKA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RELATION_1
--------------------------------------------------------

  ALTER TABLE "IE88244"."RELATION_1" ADD CONSTRAINT "RELATION_1_PK" PRIMARY KEY ("KLIENCI_ID_KLIENTA", "REZERWACJE_ID_REZERWACJI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IE88244"."RELATION_1" MODIFY ("KLIENCI_ID_KLIENTA" NOT NULL ENABLE);
  ALTER TABLE "IE88244"."RELATION_1" MODIFY ("REZERWACJE_ID_REZERWACJI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DOSTAWCY
--------------------------------------------------------

  ALTER TABLE "IE88244"."DOSTAWCY" ADD CONSTRAINT "DOSTAWCY_PK" PRIMARY KEY ("ID_DOSTAWCY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IE88244"."DOSTAWCY" MODIFY ("ID_DOSTAWCY" NOT NULL ENABLE);
  ALTER TABLE "IE88244"."DOSTAWCY" MODIFY ("KIEROWNIK_ID_KIEROWNIKA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table P£ATNOŒCI
--------------------------------------------------------

  ALTER TABLE "IE88244"."P£ATNOŒCI" ADD CONSTRAINT "P£ATNOŒCI_PK" PRIMARY KEY ("ID_P£ATNOŒCI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IE88244"."P£ATNOŒCI" MODIFY ("ID_P£ATNOŒCI" NOT NULL ENABLE);
  ALTER TABLE "IE88244"."P£ATNOŒCI" MODIFY ("RACHUNKI_ID_RACHUNKU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DANIE
--------------------------------------------------------

  ALTER TABLE "IE88244"."DANIE" ADD CONSTRAINT "DANIE_PK" PRIMARY KEY ("ID_DANIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IE88244"."DANIE" MODIFY ("ID_DANIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table DANIE
--------------------------------------------------------

  ALTER TABLE "IE88244"."DANIE" ADD CONSTRAINT "DANIE_MENU_FK" FOREIGN KEY ("MENU_ID_MENU")
	  REFERENCES "IE88244"."MENU" ("ID_MENU") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DOSTAWCY
--------------------------------------------------------

  ALTER TABLE "IE88244"."DOSTAWCY" ADD CONSTRAINT "DOSTAWCY_KIEROWNIK_FK" FOREIGN KEY ("KIEROWNIK_ID_KIEROWNIKA")
	  REFERENCES "IE88244"."KIEROWNIK" ("ID_KIEROWNIKA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table P£ATNOŒCI
--------------------------------------------------------

  ALTER TABLE "IE88244"."P£ATNOŒCI" ADD CONSTRAINT "P£ATNOŒCI_RACHUNKI_FK" FOREIGN KEY ("RACHUNKI_ID_RACHUNKU")
	  REFERENCES "IE88244"."RACHUNKI" ("ID_RACHUNKU") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRACOWNICY
--------------------------------------------------------

  ALTER TABLE "IE88244"."PRACOWNICY" ADD CONSTRAINT "PRACOWNICY_KIEROWNIK_FK" FOREIGN KEY ("KIEROWNIK_ID_KIEROWNIKA")
	  REFERENCES "IE88244"."KIEROWNIK" ("ID_KIEROWNIKA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RACHUNKI
--------------------------------------------------------

  ALTER TABLE "IE88244"."RACHUNKI" ADD CONSTRAINT "RACHUNKI_PRACOWNICY_FK" FOREIGN KEY ("PRACOWNICY_ID_PRACOWNIKA")
	  REFERENCES "IE88244"."PRACOWNICY" ("ID_PRACOWNIKA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RELATION_1
--------------------------------------------------------

  ALTER TABLE "IE88244"."RELATION_1" ADD CONSTRAINT "RELATION_1_KLIENCI_FK" FOREIGN KEY ("KLIENCI_ID_KLIENTA")
	  REFERENCES "IE88244"."KLIENCI" ("ID_KLIENTA") ENABLE;
  ALTER TABLE "IE88244"."RELATION_1" ADD CONSTRAINT "RELATION_1_REZERWACJE_FK" FOREIGN KEY ("REZERWACJE_ID_REZERWACJI")
	  REFERENCES "IE88244"."REZERWACJE" ("ID_REZERWACJI") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REZERWACJE
--------------------------------------------------------

  ALTER TABLE "IE88244"."REZERWACJE" ADD CONSTRAINT "REZERWACJE_STOLIKI_FK" FOREIGN KEY ("STOLIKI_ID_STOLIKA")
	  REFERENCES "IE88244"."STOLIKI" ("ID_STOLIKA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SK£ADNIKI
--------------------------------------------------------

  ALTER TABLE "IE88244"."SK£ADNIKI" ADD CONSTRAINT "SK£ADNIKI_DANIE_FK" FOREIGN KEY ("DANIE_ID_DANIA")
	  REFERENCES "IE88244"."DANIE" ("ID_DANIA") ENABLE;
  ALTER TABLE "IE88244"."SK£ADNIKI" ADD CONSTRAINT "SK£ADNIKI_DOSTAWCY_FK" FOREIGN KEY ("DOSTAWCY_ID_DOSTAWCY")
	  REFERENCES "IE88244"."DOSTAWCY" ("ID_DOSTAWCY") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STOLIKI
--------------------------------------------------------

  ALTER TABLE "IE88244"."STOLIKI" ADD CONSTRAINT "STOLIKI_RACHUNKI_FK" FOREIGN KEY ("RACHUNKI_ID_RACHUNKU")
	  REFERENCES "IE88244"."RACHUNKI" ("ID_RACHUNKU") ENABLE;
